// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  firebase: {
    projectId: 'glossy-beach-188721',
    appId: '1:124732544623:web:6f6d5c16b9125a016a9f9a',
    databaseURL: 'https://glossy-beach-188721.firebaseio.com',
    storageBucket: 'glossy-beach-188721.appspot.com',
    locationId: 'europe-west',
    apiKey: 'AIzaSyAm8IDZXWWnbIIbOeim367vtgUhWIHAhxg',
    authDomain: 'glossy-beach-188721.firebaseapp.com',
    messagingSenderId: '124732544623',
    measurementId: 'G-6PBF9E061X',
  },
  production: false,
  version: env['npm_package_version'] + '-dev',
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'pt-PT'],
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
