// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm8IDZXWWnbIIbOeim367vtgUhWIHAhxg',
    appId: '1:124732544623:web:6f6d5c16b9125a016a9f9a',
    messagingSenderId: '124732544623',
    projectId: 'glossy-beach-188721',
    authDomain: 'glossy-beach-188721.firebaseapp.com',
    databaseURL: 'https://glossy-beach-188721.firebaseio.com',
    storageBucket: 'glossy-beach-188721.appspot.com',
    measurementId: 'G-6PBF9E061X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7WGXTVmyS1ASy7sF707gRd5BGhBdXG4g',
    appId: '1:124732544623:android:103924167a2f61946a9f9a',
    messagingSenderId: '124732544623',
    projectId: 'glossy-beach-188721',
    databaseURL: 'https://glossy-beach-188721.firebaseio.com',
    storageBucket: 'glossy-beach-188721.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoQW2lLNeGaYhFWpM0N8pNxT9PCTiXs5E',
    appId: '1:124732544623:ios:0297a6b2991d16526a9f9a',
    messagingSenderId: '124732544623',
    projectId: 'glossy-beach-188721',
    databaseURL: 'https://glossy-beach-188721.firebaseio.com',
    storageBucket: 'glossy-beach-188721.appspot.com',
    iosClientId: '124732544623-ol94i37t1rsq53m86h8aqg5srnv1l30p.apps.googleusercontent.com',
    iosBundleId: 'com.aborla.app',
  );
}
