name: ABorla
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  mobx_codegen: ^2.0.5+2
  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  path_provider: ^2.0.9
  dio: ^4.0.4
  hive_flutter: ^1.1.0
  hive: ^2.0.5
  font_awesome_flutter: ^9.2.0
  collection: ^1.15.0
  dio_log: ^2.0.2
  shared_preferences: ^2.0.13
  uuid: ^3.0.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: 1.1.2
  build_runner: ^2.1.7
  json_serializable:
  lints:


flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
